name: Github zuimeiawallpaper download

 

on:

    push:

        branches:

            - master

    schedule:

        - cron: '0 11 * * *'

jobs:

    build:

        runs-on: ubuntu-latest

 

        steps:

            - name: Checkout codes

              uses: actions/checkout@v2

            - name: Use Node.js

              uses: actions/setup-node@v1

              with:

                node-version: '12.x'
            - name: delete
              run: |
                   rm -rf ./images/daily/*.jpg
             
            - name: Run

              
              run: npm install
                        
            - run: node zuimeiawallpaper.js
              env:
                  botapi: ${{ secrets.botapi }}
                  chatid: ${{ secrets.chatid }}

            - name: Upload to this repo

              run: |

                git config --global user.name "wudongdefeng"

                git config --global user.email "32961310+wudongdefeng@users.noreply.github.com"

                git add .

                git commit -m 'upload daily zuimeia wallpaper' 

                git push -u origin master
